#!/bin/sh

#Host pkg-config script to run on x86, targeting armv7a cross compile
#Tested on pkg-config 0.23 (from arm-arago-linux TI)
#Tested on pkg-config 0.25 (from arm-linux linaro)
#Will not work on pkg-config 0.22 (from 10.04)
export LINUX_DEVKIT=/home/prabindh/ti-sdk-am335x-evm-06.00.00.00/linux-devkit/sysroots/armv7ahf-vfp-neon-3.2-oe-linux-gnueabi/
export ROOTFS=/home/prabindh/ti-sdk-am335x-evm-06.00.00.00/filesystem
#unset this first then set libdir correctly
export PKG_CONFIG_DIR=
export PKG_CONFIG_LIBDIR=${LINUX_DEVKIT}/usr/lib/pkgconfig
export PKG_CONFIG_SYSROOT_DIR=${LINUX_DEVKIT}
#Below is needed for 0.25
export PKG_CONFIG_PATH=${LINUX_DEVKIT}/usr/lib/pkgconfig
/home/prabindh/ti-sdk-am335x-evm-06.00.00.00/linux-devkit/sysroots/i686-arago-linux/usr/bin/pkg-config --define-variable=prefix=${LINUX_DEVKIT}/usr "$@"

#/opt/toolchain-4.5.3-dynamic/arago-2011.09/armv7a/bin/pkg-config "$@"
